{% set name = "async-timeout" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d9321a7a3d5a6a5e187e824d2fa0793ce379a202935782d555d6e9d2735677d3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - typing-extensions >=3.6.5

test:
  imports:
    - async_timeout
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/aio-libs/async_timeout
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Timeout context manager for asyncio programs
  dev_url: http://github.com/aio-libs/async_timeout

extra:
  recipe-maintainers:
    - sodre
    - carlodri
    - ocefpaf
