{% set name = "async-timeout" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d87a4e8adba8ededb52e579ce6bc8276985888913620c935094c2276fd83382

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3

test:
  imports:
    - async_timeout

about:
  home: http://github.com/aio-libs/async_timeout
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Timeout context manager for asyncio programs
  dev_url: http://github.com/aio-libs/async_timeout

extra:
  recipe-maintainers:
    - sodre
    - carlodri
