appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gzj/tgKidqaG8kR4xM4Q2QY4T0443OzVP37YrddJBiQDJWApwF+oczOlfRyLU7r9RIX/GATp3n1xfAsIm+7C9MNROXyhfx2n55tbeIRvFob9nmZraVaIp+0JC+/i7TQtKDWOCJLC1Lw6kwt8X+ukq1T3NTe+39BgkazZqHp433HI4EhneCnTA5Zpt7Y2Ot2w0nnUr0gD/ym7OJvbQ6l+Ig3tgCkH5gkZYdTV8Y1tcES+nN5BzUhfty430IkHCVKPXKSJS/yGWV0ql1D3Oi3rlsv8BXIJmeiU8MIjziwrBfml3csG28fm62dPnZi+WppTr51l/ng6/Xk59YSP4NpXA3Tb3jicB6ah2S6dySNuy+4gQsxkybbcmrkMpwUrsnD3vDRfqNcvV8PEmlbg3YMUSOakTxuKRmel2qnp1e9gba7MNpFDS2a4+eykC6tXqX6UOQwBdlAfSSQ3pryt7Pq9yKPNsEivUGQftepNcKyacIWk+5hwZ628mTkOoVLWJz4IST+Z1+nFiUtIvRHoE/YwXTuu1anVtHeNV3jwCnmgUDZbGKzqKlDXp09mymeuYojsBhO+eY5Wnk7r+EjzO50PQY/pD/j5tSzfO2/DT+udJhAQ56ai0RapDY3qMvcmBDSZRP6AJg1dRMM7k4EA6IJPSyeFktDTxmJz1JMCKS5CgnM=}
