travis:
  secure:
    BINSTAR_TOKEN: DPCwb8Rj2mCGRDAaqlOLSbjeMa61bGAuRvq4OXJMrmHBwCBE5SgHw5oCZYluVtIxhhIw83N7J/VrvnB46+Vzl0XPmECjw8E9x5LtuPuLKSIjIgWOwjIT5sEzVfxBj7X1AhMvqcGLQOPWbP3ezwZZK/CNo/sOGWWTgCUk8nO2Q3s5uh1D7c0+TJD+nIuh1WeZtXwZIAvG5lMgDD6dRuelhcTq+gVYt+mt5g4fQwgHYilKDWdUbKmwBQlaCB4gWhodH1Zg1fsD4UDVSNbsUrhjnO4g0yfkVDhMhUdRYwOWOL/7bmOE+rLpGRnXO2zbhry/8cagPvdg5tXdB1J8NEwoI2UumtBwzGbfxAQ5pA7sLZcg0M2Y6ufC6zBStznfMQjM+1X/gbvzRMEQwWa7tyL44uCn1AXziizPoW49wW0rtKQ0q/c1fKPdkz6TqExEdoTrvok2p57NhBniwF0muP/qHd/Gs4bb2421/KI2KfxfFH87oZvGJxBv+2w2VMVagI5p9nfZc1QV42kaYF+F9HcvrcWKP/LniltG3H2DD7b8xdal4FPHKXG62cQiUkOD/s+7+xHpVybv1r/BZCz3W+3MFZK1HZR6RQaJ59W1UNXR/jzhTkLAo1HaAt7NH7UJybPCXl3g30LfdXneTuMKrknuImmWwsy7ZVpiAGctlIfNC6E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
